name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_WORKING_DIR: two-tier-architecture

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.x

      - name: Terraform Init
        run: terraform init
        working-directory: two-tier-architecture

      - name: Terraform Validate
        run: terraform validate
        working-directory: two-tier-architecture

      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Terraform tfcost
        uses: robertpeteuil/tfcost@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          working_directory: two-tier-architecture

      - name: Terraform Plan
        run: cd two-tier-architecture && terraform plan
        id: plan

      # - name: Terraform Apply
      #   if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
      #   run: cd two-tier-architecture && terraform apply -auto-approve
