name: Terraform CI

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    # Uncomment the following step to enable Terraform Apply
    # Make sure to set up the proper environment variables, such as AWS credentials, before running this step
    #
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
