name: Terraform CI

on:

  push:
    branches:
      - main
      - develop

env:
  TF_WORKING_DIR: two-tier-architecture

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Change working directory
      run: echo "TF_WORKING_DIR=${{ env.TF_WORKING_DIR }}" >> $GITHUB_ENV
      shell: bash

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    # Uncomment the following step to enable Terraform Apply
    # Make sure to set up the proper environment variables, such as AWS credentials, before running this step
    #
    # - name: Terraform Apply
    #   run: terraform
